### ISSUE TITLE
Hangs on at least one petcat quirk

### ISSUE THREAD

**Issue by ghost** [hbekel/bpp#1]
bpp hung when it encountered this line. Just one "{SHIFT-*}" hung it too.

`b1$="{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}{SHIFT-*}"`

**Comment by hbekel** [comment]
This wasn't really documented in the petcat manual. I have now added support for all control sequences defined in the petcat source code. Thanks for reporting this.
